backend:
  name: github
  repo: lismerdev/Ara-Estilo
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "prendas"
    label: "Catálogo de Prendas"
    folder: "prendas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre de la Prenda", name: "title", widget: "string" }
      - { label: "Precio ($)", name: "price", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen de la Prenda", name: "image", widget: "image" }
      
